#配置数据库连接信息
spring:
  freemarker:
    cache: false
    charset: utf-8
    suffix: .html
  datasource:
    druid:
      username: root
      password: root123456
      url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      #2.连接池配置
      #初始化连接池的连接数量大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        #allow: 127.0.0.1
        #deny: 192.168.1.100



mybatis:
  # type-aliases-package 可有可无 批量设置别名作用：就是在mapper.xml文件中直接写类名，不配置就需要写类的全路径名
  type-aliases-package: com.fyfe.pojo
  # 必须 指定Mapper.xml文件位置
  mapper-locations: classpath:mappers/*Mapper.xml

# 如果要看日志 将mapper接口所在包的日志级别改成debug，可以在控制台打印sql
# 如果在resources里加了logback.xml的话，这里就可以不用了加了，两种方法都行
#logging:
#  level:
#    com.cctv.mapper: debug